Resolver 'sbt-plugin-releases' was overriden with wrong URL!
This is WRONG:

http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/

scala-sbt-plugin-releases is right:

http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/

$ cat ~/.sbt/sbtpluginpublish.sbt
credentials += Credentials("Artifactory Realm", "repo.scala-sbt.org", "roberto.tyley", "{DESede}1Pxxxxxxxxxxxxxxxxxxxxxx")
$ git checkout v2.6
HEAD is now at 4c14afe... Setting version to 2.6
$ sbt publish
[info] Loading global plugins from /home/rtyley/.sbt/plugins
[info] Loading project definition from /home/rtyley/development/sbt-play-artifact/project
[info] Loading project definition from /home/rtyley/.sbt/staging/d3554263077c36ff79c5/project
[info] Loading project definition from /home/rtyley/.sbt/staging/319d5a9e390942bea603/project
[warn] Potentially incompatible versions of dependencies of {file:/home/rtyley/.sbt/staging/319d5a9e390942bea603/project/}default-3480cf:
[warn]    org.scala-sbt: 0.12.2, 0.12.0
[info] Set current project to sbt-play-artifact (in build file:/home/rtyley/development/sbt-play-artifact/)
[warn] Credentials file /home/rtyley/.ivy2/.sbtcredentials does not exist
[warn] Multiple resolvers having different access mechanism configured with same name 'sbt-plugin-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] Binary version (2.10) for dependency org.scala-lang#scala-library;2.10.0
[warn] 	in com.gu#sbt-play-artifact;2.6 differs from Scala binary version in project (2.9.2).
[info] :: delivering :: com.gu#sbt-play-artifact;2.6 :: 2.6 :: release :: Wed Feb 06 16:18:49 GMT 2013
[info] 	delivering ivy file to /home/rtyley/development/sbt-play-artifact/target/scala-2.9.2/sbt-0.12/ivy-2.6.xml
[info] Packaging /home/rtyley/development/sbt-play-artifact/target/scala-2.9.2/sbt-0.12/sbt-play-artifact-2.6.jar ...
[info] Done packaging.
java.io.IOException: Access to URL http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.gu/sbt-play-artifact/scala_2.9.2/sbt_0.12/2.6/jars/sbt-play-artifact.jar was refused by the server: Unauthorized
	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:231)
	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
...
[error] (sbt-play-artifact/*:publish) java.io.IOException: Access to URL http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.gu/sbt-play-artifact/scala_2.9.2/sbt_0.12/2.6/jars/sbt-play-artifact.jar was refused by the server: Unauthorized
[error] Total time: 1 s, completed 06-Feb-2013 16:18:50